return {
	BackAccessory = "",
	FaceAccessory = "113483063665281",
	FrontAccessory = "",
	HairAccessory = "",
	HatAccessory = "",
	NeckAccessory = "",
	ShouldersAccessory = "",
	WaistAccessory = "",

	Pants = 6491023332,
	Shirt = 3711799000,

	HeadColor = Color3.fromRGB(234, 184, 146),
	LeftArmColor = Color3.fromRGB(234, 184, 146),
	LeftLegColor = Color3.fromRGB(234, 184, 146),
	RightArmColor = Color3.fromRGB(234, 184, 146),
	RightLegColor = Color3.fromRGB(234, 184, 146),
	TorsoColor = Color3.fromRGB(),
}
