return {
	[1] = {
		TimeRequired = 300,
		Reward = { Money = 500 },
	},
	[2] = {
		TimeRequired = 600,
		Reward = { Item = 4 },
	},
	[3] = {
		TimeRequired = 900,
		Reward = { Money = 1500 },
	},
	[4] = {
		TimeRequired = 1200,
		Reward = { Item = 9 },
	},
	[5] = {
		TimeRequired = 1500,
		Reward = { Money = 2500 },
	},
	[6] = {
		TimeRequired = 2100,
		Reward = { Item = 14 },
	},
	[7] = {
		TimeRequired = 3000,
		Reward = { Money = 5500 },
	},
}
