[package]
name = "synpixel/flashcast"
description = "a fine-grained alternative to FastCast"
version = "3.0.3"
license = "MIT"
authors = ["synpixel"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]