return {
	BackAccessory = "",
	FaceAccessory = "",
	FrontAccessory = "",
	HairAccessory = "133394169359452",
	HatAccessory = "",
	NeckAccessory = "",
	ShouldersAccessory = "",
	WaistAccessory = "",

	Pants = 13117288078,
	Shirt = 13117304210,

	HeadColor = Color3.fromRGB(234, 184, 146),
	LeftArmColor = Color3.fromRGB(234, 184, 146),
	LeftLegColor = Color3.fromRGB(234, 184, 146),
	RightArmColor = Color3.fromRGB(234, 184, 146),
	RightLegColor = Color3.fromRGB(234, 184, 146),
	TorsoColor = Color3.fromRGB(),
}
