return {
	BackAccessory = "",
	FaceAccessory = "",
	FrontAccessory = "",
	HairAccessory = "133122441600903",
	HatAccessory = "",
	NeckAccessory = "",
	ShouldersAccessory = "",
	WaistAccessory = "",

	Pants = 12323140632,
	Shirt = 12323147098,

	HeadColor = Color3.fromRGB(234, 184, 146),
	LeftArmColor = Color3.fromRGB(234, 184, 146),
	LeftLegColor = Color3.fromRGB(234, 184, 146),
	RightArmColor = Color3.fromRGB(234, 184, 146),
	RightLegColor = Color3.fromRGB(234, 184, 146),
	TorsoColor = Color3.fromRGB(),
}
