return {
	BackAccessory = "",
	FaceAccessory = "",
	FrontAccessory = "",
	HairAccessory = "",
	HatAccessory = "119515233776138",
	NeckAccessory = "",
	ShouldersAccessory = "",
	WaistAccessory = "",

	Pants = 6847058130,
	Shirt = 6847056749,

	HeadColor = Color3.fromRGB(234, 184, 146),
	LeftArmColor = Color3.fromRGB(234, 184, 146),
	LeftLegColor = Color3.fromRGB(234, 184, 146),
	RightArmColor = Color3.fromRGB(234, 184, 146),
	RightLegColor = Color3.fromRGB(234, 184, 146),
	TorsoColor = Color3.fromRGB(),
}
