return {
	BackAccessory = "",
	FaceAccessory = "",
	FrontAccessory = "",
	HairAccessory = "",
	HatAccessory = "6552812",
	NeckAccessory = "",
	ShouldersAccessory = "",
	WaistAccessory = "",

	Pants = 6553208,
	Shirt = 6553199,

	HeadColor = Color3.fromRGB(234, 184, 146),
	LeftArmColor = Color3.fromRGB(234, 184, 146),
	LeftLegColor = Color3.fromRGB(234, 184, 146),
	RightArmColor = Color3.fromRGB(234, 184, 146),
	RightLegColor = Color3.fromRGB(234, 184, 146),
	TorsoColor = Color3.fromRGB(),
}
